Blog_flask/app/views/main.py
from flask import Blueprint, render_template

from app.email import send_mail

main = Blueprint('main',__name__)



@main.route('/')
def index():
    return render_template('main/index.html')



@main.route('/mail/')
def send():
    send_mail('1454605360@qq.com','关于密码','email/activate',username='xiaoming')
    return 'send mail'

Blog_flask/app/views/post.py
from flask import Blueprint, flash, redirect, url_for, request, render_template
from flask_login import current_user, login_required

from app.extensions import db
from app.forms import PostForm, ReplyForm
from app.models import Post

post = Blueprint('post',__name__)

@post.route('/publish/',methods=['POST','GET'])
def publish():
    form = PostForm()
    if form.validate_on_submit():
        if current_user.is_authenticated:

            user = current_user._get_current_object()
            p = Post(content=form.content.data, title=form.title.data,user=user)
            db.session.add(p)
            flash('帖子发表成功')
            return redirect(url_for('post.publish'))
        else:
            flash('登录后才能发表，请先登录')
            return redirect(url_for('user.login'))

    page = request.args.get('page', 1, type=int)
    allpost = Post.query.filter_by(rid=0).order_by(Post.timestamp.desc())
    pagination = allpost.paginate(page, per_page=5, error_out=False)
    posts = pagination.items
    return render_template('post/publish.html', form=form, posts=posts, pagination=pagination)

#我发表的帖子
@post.route('/list/<int:id>')   #id为当前用户的id
def list(id):
    allpost = Post.query.filter_by(uid=id).order_by(Post.timestamp.desc())
    page = request.args.get('page', 1, type=int)
    pagination = allpost.paginate(page, per_page=2, error_out=False)
    posts = pagination.items
    return render_template('post/list.html',posts=posts, pagination=pagination, id=id)


@post.route('/collect/<int:id>')  #id为帖子的id
@login_required
def collect(id):
    post=Post.query.get(id)
    post.click=post.click + 1
    current_user.posts.append(post)
    db.session.add(current_user)
    return redirect(url_for('post.mycollect'))

@post.route('/discollect/<int:id>')  #id为帖子的id
@login_required
def discollect(id):
    post=Post.query.get(id)
    current_user.posts.remove(post)
    db.session.add(current_user)
    return redirect(url_for('post.mycollect'))


#收藏帖子展示
@post.route('/mycollect/')
@login_required
def mycollect():

    postlist =current_user.posts

    return render_template('post/mycollect.html', postlist=postlist)


#查看帖子详情
@post.route('/detail/<int:id>',methods=['POST','GET'])
def detail(id):
    form = ReplyForm()
    page = request.args.get('page',1,type=int)
    post = Post.query.get(id)
    allpost = Post.query.filter_by(rid=id).order_by(Post.timestamp.desc())
    pagination = allpost.paginate(page,per_page=3,error_out=False)
    posts = pagination.items
    if current_user.is_authenticated:
        if form.validate_on_submit():
            user= current_user._get_current_object()
            p = Post(content=form.content.data,rid=id,user=user)
            db.session.add(p)
            flash('帖子回复成功')
            return redirect(url_for('post.detail',id=id))
        return render_template('post/detail.html',pagination=pagination,post=post,id=id,form=form,posts=posts)
    else:
        flash('登陆后才能回复帖子')
        return redirect(url_for('user.login'))

Blog_flask/app/views/user.py
import os

from PIL import Image
from flask import Blueprint, redirect, url_for, render_template, flash, request, current_app
from flask_login import login_user, current_user, logout_user, login_required

from app.extensions import db, photos
from app.forms import RegisterForm
from app.forms.user import LoginForm, IconForm, EditForm, EmailForm
from app.models.user import User
from app.email import send_mail
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer

user = Blueprint('user',__name__)


@user.route('/register/',methods=['POST','GET'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        user = User(username =form.username.data,password = form.password.data,email = form.email.data)
        db.session.add(user)
        db.session.commit()
        token = user.generate_activate_token()
        send_mail(form.email.data,'用户激活','email/activate',token=token,username = user.username)
        flash('注册成功，请去邮箱激活')
        return redirect(url_for('main.index'))
    return render_template('user/registered.html',form = form)


@user.route('/activate/<token>')
def activate(token):
    if User.check_activate_token(token):
        flash('激活成功')
        return redirect(url_for('user.login'))
    else:
        flash('激活失败')
        return redirect(url_for('main.index'))


@user.route('/login/',methods=['POST','GET'])
def login():
    form= LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        user = User.query.filter_by(username=username).first()
        if user.verify_password(password):
            login_user(user = user,remember=form.remember.data)
            flash('登录成功')
            return redirect(request.args.get('next') or url_for('main.index'))
        else:
            flash('重新登录')
            return redirect(url_for('user.login'))

    return render_template('user/login.html',form=form)


@user.route('/profile/')
def profile():
    return render_template('user/profile.html')

@user.route('/logout/')
def logout():
    logout_user()
    flash('用户已退出登录')
    return redirect(url_for('main.index'))

#修改密码
@user.route('/edit/',methods=['GET','POST'])
@login_required  #保护路由，只有登录后才能修改密码
def edit():
    form = EditForm()
    if form.validate_on_submit():
        if current_user.verify_password(form.password.data):
            current_user.password = form.newpassword.data
            db.session.add(current_user)
            flash("密码修改成功，请重新登录")
            logout_user()
            return redirect(url_for('user.login'))
        else:
            flash('初始密码错误，请重新输入')
            return redirect(url_for('user.edit'))
    return  render_template('user/edit.html',form=form)

#修改邮箱
@user.route('/email/',methods=['GET','POST'])
@login_required
def email():
    form = EmailForm()
    if form.validate_on_submit():
        if current_user.verify_password(form.password.data):
            s = Serializer(current_app.config['SECRET_KEY'],expires_in=3600)
            token = s.dumps({'id':current_user.id,'email':form.email.data})
            send_mail(form.email.data, '账户激活', 'email/activate', token=token, username=current_user.username)
            flash('激活邮件已经发送到您的邮箱%s，请激活后再登录'%form.email.data)
            return redirect(url_for('user.logout'))
        else:
            flash('密码错误，请重新输入')
            return redirect(url_for('user.email'))
    return render_template('user/email.html',form=form)





@user.route('/icon/',methods = ['POST','GET'])
def icon():
    form = IconForm()
    if form.validate_on_submit():
        suffix = os.path.splitext(form.photo.data.filename)[1]
        name = str(current_user.id) +  random_str() + suffix
        photos.save(form.photo.data,name=name)
        pathname = os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'],name)
        img = Image.open(pathname)
        img.thumbnail((64,64))
        img.save(pathname)
        if current_user.icon!='1.jpg':
            os.remove(os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'],current_user.icon))
        current_user.icon = name
        db.session.add(current_user)
        flash('图像上传成功')
    return render_template('user/icon.html',form=form)

def random_str(length=4):
    import random
    base_str = 'qwertyuiopasdfghjklzxcvbnm'
    return ''.join(random.choice(base_str) for i in range(length))

Blog_flask/app/templates/common/base.html
{% extends 'bootstrap/base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}

{% block head %}
    {{ super() }}
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x -icon">
{% endblock %}

{% block title %}博客中心{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-inverse" style="border-radius: 0px;">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target=".navbar-collapse" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">首页</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('post.publish') }}">帖子中心</a></li>
{#                    <li><a href="{{ url_for('post.list') }}">我的发表</a></li>#}
                    <li><a href="{{ url_for('post.mycollect') }}">我的收藏</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                        <li><a href="{{ url_for('post.list',id=current_user.id) }}"><img src="{{ url_for('static',filename='upload/'+current_user.icon) }}" alt=""
                                 style="width: 32px;height: 32px;margin-top: 9px;border-radius: 16px;"></a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">{{ current_user.username }}<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{{ url_for('user.profile') }}">用户信息</a></li>
                                <li><a href="{{ url_for('user.edit') }}">修改密码</a></li>
                                <li><a href="{{ url_for('user.email') }}">修改邮箱</a></li>
                                <li><a href="{{ url_for('user.icon') }}">修改头像</a></li>
                            </ul>
                        </li>
                        <li><a href="{{ url_for('user.logout') }}">退出</a></li>
                    {% else %}
                        <li><a href="{{ url_for('user.login') }}">登录</a></li>
                        <li><a href="{{ url_for('user.register') }}">注册</a></li>
                    {% endif %}
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
    </nav>
{% endblock %}

{% block content %}

    <div class="container">
        {# 展示flash消息 #}
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                {{ message }}
            </div>
        {% endfor %}

        {% block page_content %}
            <h1>默认内容</h1>
        {% endblock %}
    </div>

{% endblock %}

{% block scripts %}
    {{ super() }}

    {{ moment.include_moment() }}

    {{ moment.locale('zh-CN') }}
{% endblock %}

Blog_flask/app/templates/common/macro.html
{% macro show_pagination(pagination, endpoint) %}
<nav aria-label="Page navigation">
    <ul class="pagination">
        {# 上一页 #}
        <li {% if not pagination.has_prev %}class="disabled"{% endif %}>
            <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{% else %}#{% endif %}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>

        {# 中间页码 #}
        {% for p in pagination.iter_pages() %}
            {% if p %}
                <li {% if pagination.page == p %}class="active"{% endif %}><a href="{{ url_for(endpoint, page=p, **kwargs) }}">{{ p }}</a></li>
            {% else %}
                <li><a href="#">&hellip;</a></li>
            {% endif %}
        {% endfor %}

        {# 下一页 #}
        <li {% if not pagination.has_next %}class="disabled"{% endif %}>
            <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{% else %}#{% endif %}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>
{% endmacro %}