Blog_flask/app/models/post.py
from _datetime import datetime

from sqlalchemy import Column, Integer, Text, DateTime, ForeignKey

from app.extensions import db

user_posts = db.Table(
    'user_post',
    Column('user_id',Integer,db.ForeignKey('users.id')),
    Column('post_id',Integer,db.ForeignKey('posts.id')),
)


class Post(db.Model):
    __tablename__='posts'
    id = Column(Integer,primary_key=True)
    rid = Column(Integer,index=True,default=0)
    title = Column(Text)
    content = Column(Text)
    click = Column(Integer,default=0)
    timestamp = Column(DateTime,default=datetime.utcnow)

    users = db.relationship('User',backref = 'posts',secondary = user_posts,lazy='dynamic')

    uid = db.Column(Integer,ForeignKey('users.id'))

Blog_flask/app/forms/post.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField, StringField
from wtforms.validators import DataRequired, Length


class PostForm(FlaskForm):
    title = StringField('',render_kw={'placeholder':'标题'},validators=[DataRequired(),Length(3,50,message='标题太长了（3~50个字符）')])
    content = TextAreaField('',render_kw={'placeholder':'这一刻的想法...'},validators=[DataRequired(),Length(3,128,message='说话请注意分寸（3~128个字符）')])
    submit = SubmitField('发表')




class ReplyForm(FlaskForm):
    content = TextAreaField('',render_kw={'placeholder':'这一刻的想法...'},validators=[DataRequired(),Length(3,128,message='说话请注意分寸（3~128个字符）')])
    submit = SubmitField('发表')

Blog_flask/app/views/post.py
from flask import Blueprint, flash, redirect, url_for, request, render_template
from flask_login import current_user, login_required

from app.extensions import db
from app.forms import PostForm, ReplyForm
from app.models import Post

post = Blueprint('post',__name__)

@post.route('/publish/',methods=['POST','GET'])
def publish():
    form = PostForm()
    if form.validate_on_submit():
        if current_user.is_authenticated:

            user = current_user._get_current_object()
            p = Post(content=form.content.data, title=form.title.data,user=user)
            db.session.add(p)
            flash('帖子发表成功')
            return redirect(url_for('post.publish'))
        else:
            flash('登录后才能发表，请先登录')
            return redirect(url_for('user.login'))

    page = request.args.get('page', 1, type=int)
    allpost = Post.query.filter_by(rid=0).order_by(Post.timestamp.desc())
    pagination = allpost.paginate(page, per_page=5, error_out=False)
    posts = pagination.items
    return render_template('post/publish.html', form=form, posts=posts, pagination=pagination)

#我发表的帖子
@post.route('/list/<int:id>')   #id为当前用户的id
def list(id):
    allpost = Post.query.filter_by(uid=id).order_by(Post.timestamp.desc())
    page = request.args.get('page', 1, type=int)
    pagination = allpost.paginate(page, per_page=2, error_out=False)
    posts = pagination.items
    return render_template('post/list.html',posts=posts, pagination=pagination, id=id)


@post.route('/collect/<int:id>')  #id为帖子的id
@login_required
def collect(id):
    post=Post.query.get(id)
    post.click=post.click + 1
    current_user.posts.append(post)
    db.session.add(current_user)
    return redirect(url_for('post.mycollect'))

@post.route('/discollect/<int:id>')  #id为帖子的id
@login_required
def discollect(id):
    post=Post.query.get(id)
    current_user.posts.remove(post)
    db.session.add(current_user)
    return redirect(url_for('post.mycollect'))


#收藏帖子展示
@post.route('/mycollect/')
@login_required
def mycollect():

    postlist =current_user.posts

    return render_template('post/mycollect.html', postlist=postlist)


#查看帖子详情
@post.route('/detail/<int:id>',methods=['POST','GET'])
def detail(id):
    form = ReplyForm()
    page = request.args.get('page',1,type=int)
    post = Post.query.get(id)
    allpost = Post.query.filter_by(rid=id).order_by(Post.timestamp.desc())
    pagination = allpost.paginate(page,per_page=3,error_out=False)
    posts = pagination.items
    if current_user.is_authenticated:
        if form.validate_on_submit():
            user= current_user._get_current_object()
            p = Post(content=form.content.data,rid=id,user=user)
            db.session.add(p)
            flash('帖子回复成功')
            return redirect(url_for('post.detail',id=id))
        return render_template('post/detail.html',pagination=pagination,post=post,id=id,form=form,posts=posts)
    else:
        flash('登陆后才能回复帖子')
        return redirect(url_for('user.login'))

Blog_flask/app/templates/post/detail.html
{% extends 'common/base.html' %}

{% from 'common/macro.html' import show_pagination %}

{% block title %}帖子回复{% endblock %}

{% block page_content %}
    <h3>帖子详情</h3>
    {{ wtf.quick_form(form) }}

     <div class="media">
            <div class="media-left">
                <a href="#">
                    <img class="media-object" src="{{ url_for('static', filename='upload/'+post.user.icon) }}" alt="头像" style="height: 64px; width: 64px;">
                </a>
            </div>
            <div class="media-body">
                <div style="float: right;">{{ moment(post.timestamp).fromNow() }}</div>
                <h4 class="media-heading">{{ post.user.username }}</h4>
                <h3>{{ post.title }}</h3>
                {{ post.content }}
                <div style="float: right;">收藏数量：{{ post.click }}</div>
            </div>
        </div>

    <h3>网友回帖</h3>

    {% for p in posts %}
        <hr />
        <div class="media">
            <div class="media-left">
                <a href="#">
                    <img class="media-object" src="{{ url_for('static', filename='upload/'+p.user.icon) }}" alt="头像" style="height: 64px; width: 64px;">
                </a>
            </div>
            <div class="media-body">
                <div style="float: right;">{{ moment(p.timestamp).fromNow() }}</div>
                <h4 class="media-heading">{{ p.user.username }}</h4>
                <h3>{{ p.title }}</h3>
                {{ p.content }}
            </div>
        </div>
    {% endfor %}
    <hr />
    {# 分页构造url时的额外参数 #}
    {{ show_pagination(pagination, 'post.detail', id=id) }}
{% endblock %}

Blog_flask/app/templates/post/list.html
{% extends 'common/base.html' %}

{% from 'common/macro.html' import show_pagination %}

{% block title %}我的帖子{% endblock %}

{% block page_content %}

    {# 遍历展示帖子 #}
    {% for p in posts %}
        <hr />
        <div class="media">
            <div class="media-left">
                <a href="#">
                    <img class="media-object" src="{{ url_for('static', filename='upload/'+p.user.icon) }}" alt="头像" style="height: 64px; width: 64px;">
                </a>
            </div>
            <div class="media-body">
                <div style="float: right;">{{ moment(p.timestamp).fromNow() }}</div>
                <h4 class="media-heading">{{ p.user.username }}</h4>
                <h3>{{ p.title }}</h3>
                {{ p.content }}
            </div>
        </div>
    {% endfor %}
    <hr />
    {# 分页构造url时的额外参数 #}
    {{ show_pagination(pagination, 'post.list', id=id) }}
{% endblock %}

Blog_flask/app/templates/post/mycollect.html
{% extends 'common/base.html' %}

{#{% from 'common/macro.html' import show_pagination %}#}

{% block title %}帖子收藏{% endblock %}

{% block page_content %}
<div class="page-header"><h1>帖子收藏列表</h1></div>
    {# 遍历展示帖子 #}
    {% for p in postlist %}
        <hr />
        <div class="media">
            <div class="media-left">
                <a href="#">
                    <img class="media-object" src="{{ url_for('static', filename='upload/'+p.user.icon) }}" alt="头像" style="height: 64px; width: 64px;">
                </a>
            </div>
            <div class="media-body">
                <div style="float: right;">{{ moment(p.timestamp).fromNow() }}</div>
                <h4 class="media-heading">{{ p.user.username }}</h4>
                {{ p.content }}
                 <div style="float:right;"><a href="{{ url_for('post.discollect',id =p.id) }}">取消收藏</a></div>
            </div>
        </div>
    {% endfor %}
    <hr />
{#  {{ show_pagination(postlist, 'post.mycollect') }}#}
{% endblock %}

Blog_flask/app/templates/post/publish.html
{% extends 'common/base.html' %}

{% from 'common/macro.html' import show_pagination %}

{% block title %}我的发表{% endblock %}

{% block page_content %}
    {{ wtf.quick_form(form) }}

    {# 遍历展示帖子 #}
    {% for p in posts %}
        <hr />
        <div class="media">
            <div class="media-left">
                <a href="#">
                    <a href="{{ url_for('post.detail',id = p.id ) }}"><img class="media-object" src="{{ url_for('static', filename='upload/'+p.user.icon) }}" alt="头像" style="height: 64px; width: 64px;"></a>
                </a>
            </div>
            <div class="media-body">
                <div style="float: right;">{{ moment(p.timestamp).fromNow() }}</div>
                <h4 class="media-heading">{{ p.user.username }}</h4>
                <h3><a href="{{ url_for('post.detail',id = p.id ) }}">{{ p.title }}</a></h3>
                {{ p.content }}
                <div style="float:right;"><a href="{{ url_for('post.collect',id=p.id) }}">收藏</a>&nbsp;<a href="{{ url_for('post.detail',id = p.id ) }}">评论</a></div>
            </div>
        </div>
    {% endfor %}
    <hr />
    {# 分页构造url时的额外参数 #}
    {{ show_pagination(pagination, 'post.publish') }}
{% endblock %}